# 参考官网 https://circleci.com/docs/2.0/language-android/#sample-configuration
# Configuring CircleCI - CircleCI  https://circleci.com/docs/2.0/configuration-reference/#jobs
version: 2

# 引用变量
references:
  cache_key_jars: &cache_key_jars
    # key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
    key: jars-{{ checksum "build.gradle.kts" }}
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_jars
      - run:
          name: 修改权限配置
          command: sudo chmod +x ./gradlew
      - run:
          name: 下载依赖
          command: ./gradlew lint
      - save_cache:
          <<: *cache_key_jars
          paths:
            - ~/.gradle
      - run:
          name: 运行单元测试
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: 运行编译(debug)
          command: ./gradlew assembleDebug
      - run:
          name: 运行编译(release)
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_test_results:
          path: app/build/test-results